name: CI - Arabic AI Utils Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x, 22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests
        run: npm test

      - name: Run test coverage
        run: npm run test:coverage

      - name: Upload coverage to Codecov
        if: matrix.node-version == '20.x'
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella

      - name: Run example demos
        run: |
          echo "🔧 Testing main example..."
          node example.js

          echo "🔧 Testing dialect converter demo..."
          node tools/dialect-converter/examples/demo.js || echo "Demo completed"

          echo "✅ All examples completed successfully"

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check package.json format
        run: |
          npm run start --dry-run

  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: npm audit --audit-level=moderate

  rtl-validation:
    runs-on: ubuntu-latest
    name: RTL Support Validation

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Test RTL functionality
        run: |
          node -e "
          const { helpers } = require('./index');

          // Test RTL detection
          const arabicText = 'نص عربي للاختبار';
          const direction = helpers.detectTextDirection(arabicText);

          console.log('🌐 Testing RTL Support...');
          console.log('Text:', arabicText);
          console.log('Direction:', direction);
          console.log('Is Arabic:', helpers.isArabic(arabicText));
          console.log('With RTL marks:', helpers.wrapRTL(arabicText));

          if (direction !== 'rtl') {
            console.error('❌ RTL detection failed!');
            process.exit(1);
          } else {
            console.log('✅ RTL support working correctly!');
          }"
